sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson
        url_params:
            api_key: mapzen-tDHBHDp
        max_zoom: 16
    normals:
        type: Raster
        url: https://tile.mapzen.com/mapzen/terrain/v1/normal/{z}/{x}/{y}.png
        url_params:
            api_key: mapzen-tDHBHDp
        max_zoom: 15

styles: 
    terrain-envmap:
        base: raster
        lighting: false
        raster: normal
        shaders:
            uniforms:
                u_scale: .5
                u_envmap: ../img/matball01.jpg
            blocks:
                global: |
                    // Simplified view-independent environment map
                    vec4 applyEnvmap (in sampler2D _tex, in vec3 _normal) {
                        vec2 uv = 0.5 * _normal.xy + 0.5;
                        return texture2D(_tex, uv);
                    }
                color: |                    
                    normal.z *= u_scale;
                    normal = normalize(normal);
                    color = applyEnvmap(u_envmap, normal);

layers:
    terrain:
        data: { source: normals, layer: _default }
        draw:
            terrain-envmap:
                order: 0

    water:
        data: { source: mapzen }
        filter:
            - boundary: true
            - kind: [river, stream]
        draw:
            lines: 
                order: 2
                color: [.3, .3, .3]
                width: 1px

    places:
        data: { source: mapzen }
        filter: 
            kind: [city]
        draw:
            text:
                font:
                    fill: white
                    size: 16px
                    stroke: { color: '#444', width: 4px}
